---  
- name: create public CA key
  command:
    cmd: "openssl req -x509 -new -key {{ CA_dir }}/{{ CA_file }}.key -sha256 -days 1825 -out {{ CA_dir }}/{{ CA_file }}.pem -passin pass:{{ ca_priv_pass }} -subj {{ subj_string }} -batch"
    creates: "{{ CA_file }}.pem"
  notify: update keys

