---
# tasks file for ntp
# For info on ntp with chrony: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-configuring_ntp_using_the_chrony_suite
- name: make sure chronyd is installed
  dnf:
    name: chrony
    state: latest    
    update_cache: yes 
