---
# tasks file for dns
- name: "Make sure bind is installed"
  dnf:
    name: bind
    state: present
    
- name: "Make sure bind-utils is installed for debugging dns"
  dnf:
    name: bind-utils
    state: present

- name: Update named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: named
    group: named
    mode: '0600'
  notify: dns up

- name: Update lan.zone
  template:
    src: lan.zone.j2
    dest: /var/named/lan.zone
    owner: named
    group: named
    mode: '0600'
  notify: dns up

- name: Update reverse lan.zone
  template:
    src: reverse_lan_zone.j2
    dest: "{% set ip_reverse = '.'.join((sub_nets.lan.split('/')[0].split('.')|reverse)[1:]) %}/var/named/{{ip_reverse}}.in-addr.arpa"
    owner: named
    group: named
    mode: '0600'
  notify: dns up
    
- name: "Make sure bind is enabled and running"
  service:
    name: named
    enabled: yes
    state: started
    
# firewall rules
- name: "Let dns queries through"
  firewalld:
    zone: internal
    service: dns
    permanent: yes
    immediate: yes
    state: enabled