---
# tasks file for dns
- name: Update named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: named
    group: named
    mode: '0600'
  notify: dns up

- name: Update lan.zone
  template:
    src: lan.zone.j2
    dest: /var/named/lan.zone
    owner: named
    group: named
    mode: '0600'
  notify: dns up

- name: Update reverse lan.zone
  template:
    src: reverse_lan_zone.j2
    dest: "/var/named/{{ int_nets.lan|ansible.utils.ipaddr('network')|reverse }}.in-addr.arpa"
    owner: named
    group: named
    mode: '0600'
  notify: dns up
    
- name: "Make sure bind is enabled and running"
  service:
    name: named
    enabled: yes
    state: started