---
# tasks file for kanidm
- name: Install podman
  dnf:
    name: podman
    state: latest


- name: create kanidm group
  group:
    name: kanidm
    state: present
    system: yes
  register: kanidm_group

- name: create kanidm user
  user:
    name: kanidm
    state: present
    system: yes
    create_home: no
    group: kanidm
  register: kanidm_user



- name: Pull kanidm/server:latest image
  podman_image:
    name: docker.io/kanidm/server
    tag: "{% if ansible_architecture == 'x86_64' %}x86_64_{% endif %}latest"

# - name: create kanidm volume
#   containers.podman.podman_volume:
#     state: present
#     name: kanidmd
#   register: kanidm_volume

- name: create kanidm "volume"
  ansible.builtin.file:
    state: directory
    path: "/var/kanidm"
    owner: kanidm
    group: kanidm
    mode: '0770'

- name: Copy kanidm key into volume
  copy:
    src: "/certs/key.pem"
    dest: "/var/kanidm/key.pem"
    remote_src: yes

- name: Change kanidm key owners and mode
  file:
    path: "/var/kanidm/key.pem"
    owner: root
    group: kanidm
    mode: '0640'

- name: Copy kanidm chain into volume
  copy:
    src: "/certs/chain.pem"
    dest: "/var/kanidm/chain.pem"
    remote_src: yes

- name: Change kanidm chain owners and mode
  ansible.builtin.file:
    path: "/var/kanidm/chain.pem"
    owner: root
    group: kanidm
    mode: '0640'

- name: Make configuration file, perform initial setup if needed
  include_tasks: change_server_toml.yml

- name: Create kanidm pod and service unit file
  containers.podman.podman_container:
    name: kanidm-main
    image: "docker.io/kanidm/server:{% if ansible_architecture == 'x86_64' %}x86_64_{% endif %}latest"
    state: present
    user: "{{kanidm_user.uid}}:{{kanidm_group.gid}}"
    ports:
      - "{{ kanidm_port }}:{{ kanidm_port }}"
    volume:
      - "/var/kanidm:/data"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: on-failure
      names: true

- name: Make sure kanidm is running
  service:
    name: container-kanidm-main.service
    state: started