---
# tasks file for ssl_get_cert
- name: make tempfolder
  tempfile:
    prefix: crts
    state: directory
  register: crt_folder

- name: Pull signed keys from CA host
  include_tasks: pull_signed_keys.yml
  creates: "{{ key.dir }}/{{ key.file }}.{{ key.ext }}"
  loop: "{{ key_requests }}"
  loop_control:
    loop_var: key

- name: cleanup tempfolder
  ansible.builtin.file:
    path: "{{ crt_folder.path }}"
    state: absent
  when: crt_folder.path is defined