---
# tasks file for ssl_get_cert
- name: Loop over keys for signing
  block:
  - name: make tempfolder
    local_action:
      module: ansible.builtin.tempfile
      prefix: crts
      state: directory
      path: "{{ playbook_dir }}/.tmp"
    changed_when: false
    register: crt_folder

  - name: Pull signed keys from CA host
    include_tasks: pull_signed_keys.yml
    loop: "{{ key_requests }}"
    loop_control:
      loop_var: key

  always:
  - name: cleanup tempfolder
    local_action:
      module: ansible.builtin.file
      path: "{{ crt_folder.path }}"
      state: absent
    changed_when: false
    when: crt_folder.path is defined