---
# tasks file for ssl_private
- name: Add certs folder
  file:
    state: directory
    path: "{{ priv_key.dir }}/"
    owner: root
    group: root
    mode: '0600'

# see https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/ 
- name: create private CA key
  command:
    argv:
      - "openssl"
      - "genpkey"
      - "-algorithm"
      - "{{ priv_key.encryption_alg }}"
      - "-out"
      - "{{ priv_key.dir }}/{{ priv_key.file }}"
      - "-pass"
      - "pass:{{ priv_key.pass }}"
    creates: "{{ priv_key.dir }}/{{ priv_key.file }}"