---
# tasks file for ntp_server
- name: deploy chrony.conf template
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart chronyd